/*
 * This Java source file was generated by the Gradle 'init' task.
 */
package org.mitre.synthea.exporters;

import org.junit.Test;
import static org.junit.Assert.*;

public class LibraryTest {
    @Test public void testSomeLibraryMethod() {
      // do nothing for now
    }
}
